pygments: true
markdown: kramdown
permalink: none
destination: site
exclude: README.md
keep_files: ['docs', '.svn']

# The recommended way of viewing the website on your local machine is via jekyll using
# a webserver, e.g. with a command like: jekyll serve --watch --trace
# To compile the website such that it is viewable in a sane way via a file browser
# replace '/' here with the url that represents the website root dir in your file browser.
# E.g. on OS X this might be:
#url: file:///Users/andyk/Development/spark/website/site/
url: /

shark_url: http://shark.cs.berkeley.edu
graphx_url: http://amplab.github.io/graphx/
